#pragma once

enum MAIN_MENU_OPTIONS
{
	MY_ACCOUNTS = 0, FINANCES_OPTIONS, EXIT
};

enum REPORTS_MENU_OPTIONS
{
	LAST_N_DAYS_REPORT = 0, MONTHLY_REPORT, CATEGORY_REPORT, N_BIGGEST_TRANSACTIONS, GO_BACK
};

enum FINANCES_SETTINGS_OPTIONS
{
	CREATE_ACCOUNT = 0, REMOVE_ACCOUNT, ADD_CATEGORY, RETURN
};

enum YES_NO_MENU {
	YES = 0, NO
};

struct AccountData
{
	std::string name;
	double balance;
	std::string currency;
};